name: currency_converter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  connectivity_plus: ^4.0.2
  currency_picker: ^2.0.16
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  fluttertoast: ^8.2.2
  internet_connection_checker: ^1.0.0+1
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.6.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icons.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
